filetype plugin indent on
syntax enable

set number
set hlsearch
set ignorecase
set incsearch
set smartcase
set laststatus=2
set autoindent
set showcmd
set wildmenu
set ruler
set showmatch
set wildmenu
set wildmode=full
set hidden
set backspace=indent,eol,start
set showmatch
set cursorline
set mouse=a
set encoding=utf-8
set fileencodings=utf-8
set autoread
set splitbelow
set splitright
set list
set lazyredraw
set showmode
set wrapscan
