[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'call Source("airline.vim")'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_add = 'call Source("nvim-lsp.vim")'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_post_source = 'call Source("denite.vim")'
# Too early to earn dark power...

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'call Source("fugitive.vim")'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight']
hook_add = 'call Source("nerdtree.vim")'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'call Source("ale.vim")'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'call Source("quickrun.vim")'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'call Source("neoterm.vim")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


