[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'Source dein.vim'

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = 'Source sonokai.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = 'Source tokyonight.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'Source airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'Source defx.vim'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'Source coc.nvim'

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = 'Source ale.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'Source gitgutter.vim'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'Source rainbow.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'Source indentline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'Source vim-devicons.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# hook_add = 'Source polyglot.vim'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = 'Source jupytext.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'mhartington/formatter.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

# [[plugins]]
# repo = 'p00f/nvim-ts-rainbow'
# depends = ['nvim-treesitter']

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = 'Source telescope.vim'
depends = ['popup.nvim', 'plenary.nvim']

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = 'Source nvim-tree.vim'
depends = ['nvim-web-devicons']
