[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

" [[plugins]]
" repo = 'Shougo/denite.nvim'
" hook_post_source = 'source $XDG_CONFIG_HOME/nvim/plugins/denite.vim'
" Too early to earn dark power...

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-fugitive.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/ale.vim'


