[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_if = 1
hook_source = 'SourceCfg lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_cmd = ['LspInstallInfo']
on_source = 'nvim-lspconfig'
hook_source = 'SourceCfg nvim-lsp-installer'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'mhartington/formatter.nvim'
on_cmd = 'Format'
hook_source = 'SourceCfg formatter'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_if = 1
hook_post_update = 'TSUpdate'
hook_source = 'SourceCfg nvim-treesitter'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'
depends = 'nvim-treesitter'

[[plugins]]
repo = 'andymass/vim-matchup'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_if = 1
hook_source = 'SourceCfg colorizer'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_if = 1
hook_source = 'SourceCfg gitsigns'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = 'ColorScheme'
hook_source = 'SourceCfg lualine'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = ['Telescope']
on_lua = ['telescope', 'telescope.builtin']
hook_add = 'SourceCfg telescope.vim'
hook_source = 'SourceCfg telescope'
depends = ['plenary.nvim']

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
on_cmd = ['NvimTreeToggle']
hook_add = 'SourceCfg nvim-tree.vim'
hook_source = 'SourceCfg nvim-tree'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_source = 'SourceCfg nvim-autopairs'

[[plugins]]
repo = 'folke/trouble.nvim'
on_cmd = ['TroubleToggle']
on_lua = ['trouble', 'trouble.providers.telescope']
hook_add = 'SourceCfg trouble-map'
hook_source = 'SourceCfg trouble'
depends = ['nvim-web-devicons']
