[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_post_source = 'source $XDG_CONFIG_HOME/nvim/plugins/deoplete.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet'
# on_ft = ['snippet']
# on_event = 'InsertEnter'
# hook_post_source = 'source $XDG_CONFIG_HOME/nvim/plugins/neosnippet.vim'
# depends = ['neosnippet-snippets']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/jedi.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vimtex.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = 'source $XDG_CONFIG_HOME/nvim/plugins/lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_event = 'CmdlineEnter'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/anzu.vim'
