[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'mhartington/formatter.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
depends = ['nvim-treesitter']

[[plugins]]
repo = 'andymass/vim-matchup'
dependes = ['nvim-treesitter']

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = 'SourcePlugin telescope.vim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = 'SourcePlugin nvim-tree.vim'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'windwp/nvim-autopairs'

[[plugins]]
repo = 'folke/trouble.nvim'
depends = ['kyazdani42/nvim-web-devicons']
