[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'Source dein.vim'

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'Source airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ncrpy/mysnippets'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'Source coc.nvim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'Source ale.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'Source rainbow.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'Source indentline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'Source vim-devicons.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = 'Source polyglot.vim'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = 'Source jupytext.vim'
