[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'SourcePlugin dein.vim'

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = 'SourcePlugin sonokai.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = 'SourcePlugin tokyonight.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'SourcePlugin airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'SourcePlugin defx.vim'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'SourcePlugin coc.nvim'

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = 'SourcePlugin ale.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'SourcePlugin easymotion.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'SourcePlugin gitgutter.vim'

# [[plugins]]
# repo = 'luochen1990/rainbow'
# hook_add = 'SourcePlugin rainbow.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'SourcePlugin indentline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'SourcePlugin vim-devicons.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# hook_add = 'SourcePlugin polyglot.vim'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = 'SourcePlugin jupytext.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'mhartington/formatter.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
depends = ['nvim-treesitter']

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = 'SourcePlugin telescope.vim'
depends = ['popup.nvim', 'plenary.nvim']

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = 'SourcePlugin nvim-tree.vim'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'windwp/nvim-autopairs'
