[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'Source airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'Source coc.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = 'Source nvim-lsp.vim'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = 'Source denite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'Source fugitive.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'Source rainbow.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'Source indentline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight']
hook_add = 'Source nerdtree.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'Source vim-devicons.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'Source ale.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'Source quickrun.vim'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'Source neoterm.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = 'Source jupytext.vim'
