[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'
on_lua = 'cmp_nvim_lsp'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-document-symbol'
on_source = 'nvim-cmp'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = 'nvim-cmp'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lua'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'
depends = 'vim-vsnip'

[[plugins]]
repo = 'ray-x/cmp-treesitter'
on_source = 'nvim-cmp'
depends = 'nvim-treesitter'

[[plugins]]
repo = 'tzachar/cmp-tabnine'
on_source = 'nvim-cmp'
build = './install.sh'

[[plugins]]
repo = 'rinx/cmp-skkeleton'
on_source = 'nvim-cmp'
depends = 'skkeleton'

[[plugins]]
repo = 'onsails/lspkind.nvim'
on_source = 'nvim-cmp'
on_lua = 'lspkind'
