[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = 'Source deoplete.vim'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
on_event = 'InsertEnter'
depends = ['nvim-lspconfig', 'deoplete.nvim']

[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['snippet']
on_event = 'InsertEnter'
hook_post_source = 'Source neosnippet.vim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex']
merged = 0
hook_add = 'Source vimtex.vim'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']
hook_add = 'Source virtualenv.vim'

[[plugins]]
repo = 'jpalardy/vim-slime'
on_ft = ['python']

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_ft = ['python']
hook_add = 'Source vim-ipython-cell.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = 'Source lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_event = 'CmdlineEnter'
hook_add = 'Source anzu.vim'
