[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'SourceCfg dein.vim'

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = 'SourceCfg sonokai.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = 'SourceCfg tokyonight.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

# [[plugins]]
# repo    = 'vim-airline/vim-airline'
# depends = ['vim-airline-themes']
# hook_add = 'SourceCfg airline.vim'
# 
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'SourceCfg defx.vim'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = 'SourceCfg coc.nvim'

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = 'SourceCfg ale.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'SourceCfg easymotion.vim'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'
# hook_add = 'SourceCfg gitgutter.vim'

# [[plugins]]
# repo = 'luochen1990/rainbow'
# hook_add = 'SourceCfg rainbow.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'SourceCfg indentline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'SourceCfg vim-devicons.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# hook_add = 'SourceCfg polyglot.vim'

[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = 'SourceCfg jupytext.vim'
