# [[plugins]]
# repo = 'Shougo/ddc.vim'
# on_event = 'InsertEnter'
# depends = ['denops.vim']
# hook_source = 'SourceCfg ddc.vim'
# 
# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# on_source = 'ddc.vim'
# 
# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# on_source = 'ddc.vim'
# 
# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'ddc.vim'
# 
# [[plugins]]
# repo = 'LumaKernel/ddc-file'
# on_source = 'ddc.vim'
# 
# [[plugins]]
# repo = 'LumaKernel/ddc-tabnine'
# on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_event = 'CmdUndefined Skkeleton'
hook_add = 'SourceCfg skkeleton-map.vim'
hook_source = 'SourceCfg skkeleton.vim'

# [[plugins]]
# repo = 'github/copilot.vim'
# on_event = 'InsertEnter'
# on_cmd = 'Copilot'
# hook_source = 'SourceCfg copilot.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet'
# on_ft = ['snippet']
# on_event = 'InsertEnter'
# hook_post_source = 'SourceCfg neosnippet.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'
hook_source = 'SourceCfg vim-vsnip.vim'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = 'vim-vsnip'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# on_cmd = ['Denite']
# depends = ['vim-devicons', 'neomru.vim', 'neoyank.vim']
# hook_add = 'SourceCfg denite.vim'
# hook_source = 'SourceCfg denite-lazy.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# on_source = 'neoosnippet'

# [[plugins]]
# repo = 'ncrpy/mysnippets'
# on_source = 'neosnippet'

# [[plugins]]
# repo = 'Shougo/neomru.vim'
# on_cmd = ['Denite']
# 
# [[plugins]]
# repo = 'Shougo/neoyank.vim'
# on_cmd = ['Denite']

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# on_cmd = ['NERDTree']
# depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight']
# hook_add = 'SourceCfg nerdtree.vim'

# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# on_source = 'nerdtree'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']
hook_add = 'SourceCfg virtualenv.vim'

# [[plugins]]
# repo = 'jpalardy/vim-slime'
# on_ft = ['python']

# [[plugins]]
# repo = 'hanschen/vim-ipython-cell'
# on_path = ['.ipynb']
# hook_add = 'SourceCfg vim-ipython-cell.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex']

[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r', 'rmd']
branch = 'stable'
hook_add = 'SourceCfg Nvim-R.vim'

# [[plugins]]
# repo = 'cohama/lexima.vim'
# on_event = 'InsertEnter'
# hook_source = 'SourceCfg lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_event = 'CmdlineEnter'
hook_add = 'SourceCfg anzu.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_event = 'CmdlineEnter'
hook_add = 'SourceCfg quickrun.vim'
