[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

