[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
hook_source = 'Source nvim-lsp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = 'Source deoplete.vim'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
on_event = 'InsertEnter'
depends = ['nvim-lspconfig', 'deoplete.nvim']

[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['snippet']
on_event = 'InsertEnter'
hook_post_source = 'Source neosnippet.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
depends = ['vim-devicons', 'neomru.vim', 'neoyank.vim']
hook_add = 'Source denite.vim'
hook_source = 'Source denite-lazy.vim'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
on_source = 'deoplete.nvim'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# on_source = 'neoosnippet'

[[plugins]]
repo = 'ncrpy/mysnippets'
on_source = 'neosnippet'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_cmd = ['Denite']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_cmd = ['Denite']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree']
depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight']
hook_add = 'Source nerdtree.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
on_source = 'nerdtree'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']
hook_add = 'Source virtualenv.vim'

[[plugins]]
repo = 'jpalardy/vim-slime'
on_ft = ['python']

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_ft = ['.ipynb']
hook_add = 'Source vim-ipython-cell.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex']
hook_add = 'Source vimtex.vim'

[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r', 'rmd']
branch = 'stable'
hook_add = 'Source Nvim-R.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = 'Source lexima.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_event = 'CmdlineEnter'
hook_add = 'Source anzu.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'CmdlineEnter'
hook_source = 'Source fugitive.vim'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_event = 'CmdlineEnter'
hook_add = 'Source quickrun.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'VimEnter'
hook_soruce = 'Source nvim-treesitter.vim'
