[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_if = 1
hook_source = 'SourceCfg lspconfig'

# [[plugins]]
# repo = 'williamboman/nvim-lsp-installer'
# on_cmd = ['LspInstallInfo']
# on_source = 'nvim-lspconfig'
# hook_source = 'SourceCfg nvim-lsp-installer'
# depends = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
on_cmd = ['Mason']
on_source = 'nvim-lspconfig'
depends = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'mason.nvim'
hook_source = 'SourceCfg mason'
depends = ['nvim-lspconfig', 'mason.nvim']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_if = 1
hook_post_update = 'TSUpdate'
hook_source = 'SourceCfg nvim-treesitter'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'
depends = 'nvim-treesitter'

[[plugins]]
repo = 'andymass/vim-matchup'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_if = 1
hook_source = 'SourceCfg colorizer'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_if = 1
hook_source = 'SourceCfg gitsigns'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = 'ColorScheme'
hook_source = 'SourceCfg lualine'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'romgrk/barbar.nvim'
on_event = 'ColorScheme'
hook_add = 'SourceCfg barbar.vim'
hook_source = 'SourceCfg barbar'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'ColorScheme'
hook_source = 'SourceCfg indent-blankline'

# [[plugins]]
# repo = 'zbirenbaum/copilot.lua'
# on_event = 'InsertEnter'

# [[plugins]]
# repo = 'zbirenbaum/copilot-cmp'
# on_source = 'copilot.lua'
# hook_source = 'SourceCfg copilot'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = ['InsertEnter']
hook_source = 'SourceCfg nvim-cmp'

[[plugins]]
repo = 'mhartington/formatter.nvim'
on_cmd = 'Format'
hook_add = 'SourceCfg formatter-map'
hook_source = 'SourceCfg formatter'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_if = 1

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = ['Telescope']
on_lua = ['telescope', 'telescope.builtin']
hook_add = 'SourceCfg telescope-map'
hook_source = 'SourceCfg telescope'
depends = ['plenary.nvim']

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
on_cmd = ['NvimTreeToggle']
hook_add = 'SourceCfg nvim-tree.vim'
hook_source = 'SourceCfg nvim-tree'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_source = 'SourceCfg nvim-autopairs'

[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_lua = ['dap', 'dapui']
hook_add = 'SourceCfg nvim-dap'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_lua = 'dapui'
hook_add = 'SourceCfg nvim-dap-map'
hook_source = 'SourceCfg nvim-dap-ui'
depends = 'nvim-dap'

# [[plugins]]
# repo = 'theHamsta/nvim-dap-virtual-text'
# on_lua = 'dap'
# depends = ['nvim-tresitter', 'nvim-dap']

[[plugins]]
repo = 'folke/trouble.nvim'
on_cmd = ['TroubleToggle']
on_lua = ['trouble', 'trouble.providers.telescope']
hook_add = 'SourceCfg trouble-map'
hook_source = 'SourceCfg trouble'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'LinArcX/telescope-command-palette.nvim'
on_source = 'telescope.nvim'
hook_source = 'SourceCfg command-palette'
depends = ['telescope.nvim']

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_event = 'ColorScheme'
hook_source = 'SourceCfg fidget'
